package entity;
// Generated Mar 24, 2017 7:27:14 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Booking generated by hbm2java
 */
@XmlRootElement(name="booking")
@XmlAccessorType(XmlAccessType.NONE)
@Entity
@Table(name = "BOOKING")
public class Booking {
	@XmlElement(name = "id")
	private int id;
	@XmlElement(name = "room")
	private Room room;
	private Users users;
	@XmlElement(name = "datein")
	private String datein;
	@XmlElement(name = "detail")
	private String detail;
	@XmlElement(name = "quanlity")
	private int quanlity;
	@XmlElement(name = "dateout")
	private String dateout;

	public Booking() {
	}

	public Booking(int id, Room room, Users users, String datein, int quanlity, String dateout) {
		this.id = id;
		this.room = room;
		this.users = users;
		this.datein = datein;
		this.quanlity = quanlity;
		this.dateout = dateout;
	}

	public Booking(int id, Room room, Users users, String datein, String detail, int quanlity, String dateout) {
		this.id = id;
		this.room = room;
		this.users = users;
		this.datein = datein;
		this.detail = detail;
		this.quanlity = quanlity;
		this.dateout = dateout;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room", nullable = false)
	@XmlTransient
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users", nullable = false)
	@XmlTransient
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}


	@Column(name = "datein", nullable = false, length = 23)
	public String getDatein() {
		String string = datein;
		String[] parts = string.split("-");
		String part1 = parts[0];
		String part2 = parts[1];
		String part3 = parts[2];
		datein = part3 + "-" + part2 + "-" + part1;
		return this.datein;
	}

	public void setDatein(String datein) {
		this.datein = datein;
	}

	@Column(name = "detail")
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "quanlity", nullable = false)
	public int getQuanlity() {
		return this.quanlity;
	}

	public void setQuanlity(int quanlity) {
		this.quanlity = quanlity;
	}


	@Column(name = "dateout", nullable = false, length = 23)
	public String getDateout() {
		String string = dateout;
		String[] parts = string.split("-");
		String part1 = parts[0];
		String part2 = parts[1];
		String part3 = parts[2];
		dateout = part3 + "-" + part2 + "-" + part1;
		return this.dateout;
	}

	public void setDateout(String dateout) {
		this.dateout = dateout;
	}

}
